!Group
groups:
  traveller-creation: !Group
    tables:
      ageing: !Table {}
      # TODO background-skills: !Table {}
      benefits-of-rank: !Table {}
      career-summary: !Table
        continuation_empty_column: !!null
      characteristic-modifiers: !Table {}
      draft-selection: !Table {}
      injuries: !Table {}
      life-events: !Table {}
      medical-bills: !Table {}
      noble-titles: !Table {}
      pension: !Table {}
      pre-career-events: !Table {}
      # TODO skills-package: !Table {}
    groups: {}
      # TODO career: !Group {}
  skills-and-tasks: !Group
    tables:
      # TODO effect-results: !Table {}
      # TODO task-chain: !Table
      #   num_header_lines: 3
      task-difficulty: !Table {}
      # TODO timeframes: !Table {}
  combat: !Group
    tables:
      common-modifiers: !Table {}
      cover: !Table {}
  encounters-and-dangers: !Group
    tables:
      allies-and-enemies: !Table {}
      character-experience: !Table {}
      character-quirks: !Table {}
      encounter-distance: !Table {}
      # TODO encounter-modifiers: !Table {}
      experience-levels: !Table {}
      range-bands: !Table {}
      temperatures: !Table {}
    groups:
      animal: !Group
        tables:
          # TODO behaviours: !Table {}
          flight-or-fight: !Table {}
          sizes: !Table {}
      dangers: !Group
        tables:
          disease: !Table {}
          poisons: !Table
            num_header_lines: 2
      patrons-and-missions: !Group
        tables:
          random-mission: !Table {}
          random-opposition: !Table {}
          random-patrons: !Table {}
          random-targets: !Table {}
      random-encounters: !Group
        tables:
          rural: !Table {}
          starport: !Table {}
          urban: !Table {}
  trade: !Group
    tables:
      trade-goods: !Table
        type: TradeGood
  worldcreation: !Group
    tables:
      governments: !Table
        type: Government
        num_header_lines: 2
      law-levels: !Table
        type: LawLevel
        num_header_lines: 2
      trade-codes: !Table
        type: TradeCode
