!Config
groups:
  - !Group
    name: trade
    tables:
      - !Table
        name: trade-goods
  - !Group
    name: worldcreation
    tables:
      - !Table
        name: governments
        num_header_lines: 2
      - !Table
        name: law-levels
        num_header_lines: 2
      - !Table
        name: trade-codes
