!Group
groups:
  traveller-creation: !Group
    tables:
      ageing: !Table {}
      background-skills: !Table
        extraction: !TableExtraction
          add_header_row:
          - Skill and level
      benefits-of-rank: !Table {}
      career-summary: !Table
        extraction: !TableExtraction
          continuation_empty_column: !!null
      characteristic-modifiers: !Table {}
      draft-selection: !Table {}
      injuries: !Table {}
      life-events: !Table {}
      medical-bills: !Table {}
      noble-titles: !Table {}
      pension: !Table {}
      pre-career-events: !Table {}
      skills-package: !Table
        extraction: !!null
    groups: {}
      # TODO career: !Group {}
  skills-and-tasks: !Group
    tables:
      effect-results: !Table
        extraction: !TableExtraction
          continuation_empty_column: !!null
          row_num_lines: [3, 1, 5, 3, 1, 2]
      task-chain: !Table
        extraction: !TableExtraction
          num_header_lines: 3
          continuation_empty_column: !!null
          row_num_lines: [2, 2, 2, 2, 2, 2]
      task-difficulty: !Table {}
      timeframes: !Table
        extraction: !TableExtraction
          continuation_empty_column: !!null
          row_num_lines: [2, 2, 3, 2, 4, 3, 2, 2, 2, 2]
  combat: !Group
    tables:
      common-modifiers: !Table {}
      cover: !Table {}
  encounters-and-dangers: !Group
    tables:
      allies-and-enemies: !Table {}
      character-experience: !Table {}
      character-quirks: !Table {}
      encounter-distance: !Table {}
      encounter-modifiers: !Table
        extraction: !TableExtraction
          continuation_empty_column: !!null
          row_num_lines: [1, 1, 1, 1, 2, 2]
          add_header_row:
          - Circumstance
          - Modifier
      experience-levels: !Table {}
      range-bands: !Table {}
      temperatures: !Table {}
    groups:
      animal: !Group
        tables:
          behaviours: !Table
            extraction: !!null
          flight-or-fight: !Table {}
          sizes: !Table {}
      dangers: !Group
        tables:
          disease: !Table {}
          poisons: !Table
            extraction: !TableExtraction
              num_header_lines: 2
      patrons-and-missions: !Group
        tables:
          random-mission: !Table {}
          random-opposition: !Table {}
          random-patrons: !Table {}
          random-targets: !Table {}
      random-encounters: !Group
        tables:
          rural: !Table {}
          starport: !Table {}
          urban: !Table {}
  trade: !Group
    tables:
      trade-goods: !Table
        type: TradeGood
  worldcreation: !Group
    tables:
      governments: !Table
        type: Government
        extraction: !TableExtraction
          num_header_lines: 2
      law-levels: !Table
        type: LawLevel
        extraction: !TableExtraction
          num_header_lines: 2
      trade-codes: !Table
        type: TradeCode
