!Group
groups:
  traveller-creation: !Group
    tables:
      career-summary: !Table
        continuation_empty_column: !!null
  trade: !Group
    tables:
      trade-goods: !Table
        type: TradeGood
  worldcreation: !Group
    tables:
      governments: !Table
        type: Government
        num_header_lines: 2
      law-levels: !Table
        type: LawLevel
        num_header_lines: 2
      trade-codes: !Table
        type: TradeCode
