#!/usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
import sys


def main() -> None:
    try:
        subprocess.check_call(["poetry", "run", "mypy", "scripts", "src", "tests"])
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)


if __name__ == "__main__":
    main()
