#!/usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
import sys


def main() -> None:
    files = [f for f in sys.argv[1:] if not f.startswith("scripts/oneoff/")]
    if not files:
        return
    try:
        subprocess.check_call(["poetry", "run", "pylint"] + files)
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)


if __name__ == "__main__":
    main()
