name: Publish Python package
description: Publish the Python package to PyPI.

runs:
  using: composite
  steps:
    - name: Build package
      shell: bash
      run: poetry build
    - name: Publish package
      shell: bash
      run: |
        poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
        poetry publish
