name: Publish Python package
description: Publish the Python package to PyPI.

inputs:
  pypi-token:
    description: PyPI API token to use.
    required: true

runs:
  using: composite
  steps:
    - name: Build package
      shell: bash
      run: poetry build
    - name: Publish package
      shell: bash
      run: |
        poetry config pypi-token.pypi "${{ inputs.pypi-token }}"
        poetry publish
