name: Upload Python Package

runs:
  using: composite
  steps:
    - name: Build package
      run: poetry build
    - name: Publish package
      run: |
        poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
        poetry publish
