name: Setup Python

inputs:
  python-version:
    required: true

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - uses: actions/checkout@v3
  - name: Install poetry
    run: pipx install poetry
  - name: Install dependencies
    run: poetry install
