name: Setup Python
description: Sets up Python environment with Poetry and dependencies.

inputs:
  python-version:
    description: The MAJOR.MINOR version of Python to use.
    required: true

runs:
  using: composite
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install poetry
    shell: bash
    run: pipx install poetry
  - name: Use in-workspace virtual environment
    # This is required by the PyInstaller spec to find the Tabula jar.
    shell: bash
    run: poetry config virtualenvs.in-project true
  - name: Install dependencies
    shell: bash
    run: poetry install
