name: Setup Python
description: Sets up Python environment with Poetry and dependencies.

inputs:
  python-version:
    description: The MAJOR.MINOR version of Python to use.
    required: true

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - uses: actions/checkout@v3
  - name: Install poetry
    shell: bash
    run: pipx install poetry
  - name: Install dependencies
    shell: bash
    run: poetry install
