name: Create Release Assets

on:
  workflow_call:
    inputs:
      github_ref_name:
        required: true
        type: string
      upload_url:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      github_ref_name:
        description: Github reference tag, acting as a version.
        required: true
        type: string
      upload_url:
        description: Release endpoint to upload the assets to.
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        python-version: 
          - "3.11"
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Install shiv
        # Unlike other workflows, this one only needs shiv. Everything else is
        # downloaded by shiv itself. Save on installation cost/time.
        shell: bash
        run: pip install shiv
      - name: Build binary
        shell: bash
        run: |
          python3 ./scripts/dev/build_executables.py -- \
            ${{ inputs.github_ref_name }}
      - name: Package as ZIP
        shell: bash
        run: |
          python3 ./scripts/dev/build_release_zip.py -- \
            build/travdata-${{ runner.os }}-${{ runner.arch }}-${{ inputs.github_ref_name }}.zip
      - name: Upload as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: build/travdata-${{ runner.os }}-${{ runner.arch }}-${{ inputs.github_ref_name }}.zip
          asset_name: travdata-${{ runner.os }}-${{ runner.arch }}-${{ inputs.github_ref_name }}.zip
          asset_content_type: application/zip
