name: Create Release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"
      - uses: ./.github/actions/python-publish
  create-assets:
    needs: release
    uses: ./.github/workflows/create-release-assets.yml
    with:
      github_ref_name: ${{ github.ref_name }}
      upload_url: ${{ needs.release.outputs.upload_url }}
