name: Create Release Assets

on:
  workflow_call:
    inputs:
      github_ref_name:
        required: true
        type: string
      upload_url:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      github_ref_name:
        description: Github reference tag, acting as a version.
        required: true
        type: string
      upload_url:
        description: Release endpoint to upload the assets to.
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        python-version: 
          - "3.11"
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: "${{ matrix.os }}"
    steps:
      - name: Set asset filename
        id: asset_filename
        shell: bash
        run: |
          echo "ZIP=travdata-${{ runner.os }}-${{ runner.arch }}-${{ inputs.github_ref_name }}.zip" \
            >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-python.yml
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build release asset with shiv
        shell: bash
        run: |
          poetry run ./scripts/dev/build_pyinstaller_release.py -- \
            "${{ inputs.github_ref_name }}" \
            "./${{ steps.asset_filename.ZIP }}"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./${{ steps.asset_filename.ZIP }}
          asset_name: ${{ steps.asset_filename.ZIP }}
          asset_content_type: application/zip
