name: Create Release

on:
  workflow_call:
    inputs:
      github_ref_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      github_ref_name:
        description: Github reference tag, acting as a version.
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.github_ref_name }}
      - uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"
      - uses: ./.github/actions/python-publish
        with:
          pypi-token: ${{ secrets.PYPI_TOKEN }}
