[package]
name = "travdata-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
egui_inbox.workspace = true
generic-pipeline.workspace = true
hashbrown.workspace = true
itertools = "0.15.0"
log.workspace = true
pipeline.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
simplelog.workspace = true
slotmap = { version = "1.1.1", features = ["serde"] }
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

[dev-dependencies]
googletest.workspace = true
pipeline = { features = ["testing"], workspace = true }
testutils.workspace = true
